feat(Syntaxt): add redcarpet with rouge coloration
ekit3/jekyll-site pull request #3
Opened 2021-02-10 23:05 UTC by m3stash

- add search articles by category
- fix issue with copy button

2021-02-11 07:44 UTC, juwit requested changes

2021-02-11 07:44 UTC, juwit commented on _includes/header.html
> +        </select>-->
tu peux supprimer ce code au lieu de le commenter :)

2021-02-11 07:44 UTC, juwit commented on scripts/index.js
> +    const elements = document.getElementsByClassName('language-ruby highlighter-rouge');
du coup, le bouton copier apparait que pour le code ruby: 

Tu peux peut-être utiliser:

```suggestion
    const elements = document.getElementsByClassName('highlighter-rouge');
```

2021-02-11 07:59 UTC, m3stash commented on scripts/index.js
> +    const elements = document.getElementsByClassName('language-ruby highlighter-rouge');
oui en effet du coup j'avais fait ça au moment du "copier" pour être sur de ne prendre que le contenu du block code : 
`const text = e.parentElement.getElementsByTagName('code')[0].innerText;`
il me semble qu'avec juste `language-ruby highlighter-rouge` il prenait quand même le "copier" du bouton je vais re-tester.

2021-02-11 08:01 UTC, m3stash commented on _includes/header.html
> +        </select>-->
en fait lui je le gardais de côté "pour le moment" avant de savoir si oui ou non on faisait du tri sur les catégories ou pas.
mais ouai c'est pas non plus compliqué je le retirerais ce soir ^^

2021-02-11 20:50 UTC, m3stash commented on scripts/index.js
> +    const elements = document.getElementsByClassName('language-ruby highlighter-rouge');
done!

2021-02-11 20:50 UTC, m3stash commented on _includes/header.html
> +        </select>-->
done!

2021-02-12 07:23 UTC, juwit approved these changes

2021-02-12 07:23 UTC, merged